
repos:
  - repo: local
    hooks:
      - id: black
        name: black formatter
        entry: black
        language: system
        types: [python]

      - id: flake8
        name: flake8 linter
        entry: flake8
        language: system
        types: [python]

      - id: isort
        name: isort sorter
        entry: isort
        language: system
        types: [python]
